### ISSUE TITLE
object.__init__() takes no parameters

### ISSUE THREAD

**Issue by alibertozo** [niavlys/memoryKivy#6]
Hi! When I run main.py I've got this error:

[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v3.6.1 |Continuum Analytics, Inc.| (default, Mar 22 2017, 20:11:04) [MSC v.1900 64 bit (AMD64)]
[INFO              ] [Factory     ] 179 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO              ] [Text        ] Provider: sdl2
[INFO              ] [OSC         ] using <thread> for socket
[INFO              ] [Window      ] Provider: sdl2
[INFO              ] [GL          ] GLEW initialization succeeded
[INFO              ] [GL          ] OpenGL version <b'4.3.0 - Build 20.19.15.4531'>
[INFO              ] [GL          ] OpenGL vendor <b'Intel'>
[INFO              ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 4600'>
[INFO              ] [GL          ] OpenGL parsed version: 4, 3
[INFO              ] [GL          ] Shading version <b'4.30 - Build 20.19.15.4531'>
[INFO              ] [GL          ] Texture max size <16384>
[INFO              ] [GL          ] Texture max units <32>
[INFO              ] [Shader      ] fragment shader: <b"WARNING: 0:7: '' :  #version directive missing">
[INFO              ] [Shader      ] vertex shader: <b"WARNING: 0:7: '' :  #version directive missing">
[INFO              ] [Window      ] auto add sdl2 input provider
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO              ] [Audio       ] Providers: audio_sdl2 (audio_ffpyplayer ignored)
 Traceback (most recent call last):
   File "C:/dev/memoryKivy-master/main.py", line 429, in <module>
     MyAnimalsApp().run()
   File "C:\Users\abertozo\AppData\Local\Continuum\Anaconda3\envs\k36\lib\site-packages\kivy\app.py", line 802, in run
     root = self.build()
   File "C:/dev/memoryKivy-master/main.py", line 402, in build
     pb = MyPb(max=items, size_hint=(0.55,1),ml=g)
   File "C:\Users\abertozo\AppData\Local\Continuum\Anaconda3\envs\k36\lib\site-packages\kivy\uix\progressbar.py", line 40, in __init__
     super(ProgressBar, self).__init__(**kwargs)
   File "C:\Users\abertozo\AppData\Local\Continuum\Anaconda3\envs\k36\lib\site-packages\kivy\uix\widget.py", line 312, in __init__
     super(Widget, self).__init__(**kwargs)
   File "kivy\_event.pyx", line 254, in kivy._event.EventDispatcher.__init__ (kivy\_event.c:5305)
 TypeError: object.__init__() takes no parameters

Could you help me?

Thanks!

**Comment by annemariet** [comment]
Don't ask me why, but I removed the last argument on line 413 in `main.py` and it fixed the issue : `pb = MyPb(max=items, size_hint=(0.55, 1))#, ml=g)`.
I just couldn't find where that argument would be used, and I don't know if the progress bar works as expected.

**Comment by rafaeljneves** [comment]
Thanks @annemariet !  It worked for me !
